project/DeCharla/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('favicon.ico', views.get_favicon, name='favicon'),
    path('', views.login_view, name='login'),
    path('room_list/', views.room_list, name='room_list'),
    path('rooms/<int:room_id>/', views.room, name='room'),
    path('rooms/<int:room_id>/send_message/', views.send_message, name='send_message'),
    path('rooms/<int:room_id>/messages.json', views.messages_json, name='messages_json'),
    path('rooms/<int:room_id>/roomdin/', views.roomdin, name='roomdin'),
    path('rooms/<int:room_id>/send_message_din/', views.send_message_din, name='send_message_din'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('logout/', views.logout_view, name='logout_view'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('DeCharla/', include('DeCharla.urls')),
    path('login', login.as_view())
]

project/DeCharla/models.py
from django.db import models

class Room(models.Model):
    name = models.TextField()
    #creator = models.TextField(default='')
    #description = models.TextField(default='')

class Message(models.Model):
    session = models.TextField(default="")
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    sender = models.TextField(default='')
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_image = models.BooleanField(default=False)
    image_url = models.URLField(null=True, blank=True)

class Passwords(models.Model):
    password = models.CharField(max_length=128)

class Session(models.Model):
    session = models.TextField(unique=True)
    name = models.TextField()
    font_size = models.CharField(max_length=20, default='12px')
    font_family = models.CharField(max_length=50, default='Arial')



class VisitedChat(models.Model):
    chat = models.ForeignKey(Room, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    access_date = models.DateTimeField(auto_now=True)

project/DeCharla/forms.py
from django import forms

class RoomForm(forms.Form):
    room_name = forms.CharField(max_length=100)

class LoginForm(forms.Form):
    password = forms.CharField(max_length=100)

project/DeCharla/views.py
import random
import string
from xml.etree import ElementTree
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core import validators
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from .models import Room, Message, Passwords, Session, VisitedChat
import xml.etree.ElementTree as ET
import os
from django.conf import settings
from django.db.models import Count


# Función para verificar la sesión del usuario
def check_session(request):
    cookie = request.COOKIES.get("session")
    if cookie is None:
        # Si no existe la cookie, se crea una nueva y se devuelve la respuesta con la cookie establecida
        response = HttpResponse()
        random_cookie = ''.join(random.choices(string.ascii_lowercase + string.digits, k=128))
        response.set_cookie("session", random_cookie)
        return response
    if request.path != "/login":
        # Verificar si la sesión existe en la base de datos
        check = Session.objects.filter(session=cookie).exists()
    else:
        # Si la página es la de inicio de sesión, se considera que la sesión es válida
        check = True
    return check


# Vista de inicio
def index(request):
    # Verificar la sesión del usuario
    check = check_session(request)
    if not check:
        # Si no hay sesión válida, redirigir a la página de inicio de sesión
        return redirect('login')

    # Redirigir a la lista de salas
    return redirect('room_list')

# Vista de inicio de sesión
def login_view(request):
    if request.user.is_authenticated:
        # Si el usuario ya está autenticado, redirigir a la lista de salas
        return redirect('room_list')

    if request.method == 'POST':
        password = request.POST.get('password')

        if Passwords.objects.filter(password=password).exists():
            try:
                session = Session.objects.create(
                    session=''.join(random.choices(string.ascii_lowercase + string.digits, k=128)), name="Anónimo")
            except Session.DoesNotExist:
                session = Session.objects.create(session=''.join(random.choices(string.ascii_lowercase + string.digits, k=128)), name="Anónimo")

            # Establecer la sesión y el nombre de usuario en la sesión actual del usuario
            request.session['logged_in'] = True
            request.session['username'] = session.name

            response = redirect('room_list')
            response.set_cookie('session', session.session)  # Crear la cookie con el valor de la sesión
            return response
        else:
            messages.error(request, 'Contraseña incorrecta')

    return render(request, 'login.html')

# Vista de cierre de sesión
def logout_view(request):
    # Limpiar la sesión y borrar la cookie de sesión
    request.session.clear()
    response = redirect('login')
    response.delete_cookie('session')  # Borrar la cookie 'sessionid'
    return response

# Vista de la lista de salas
def room_list(request):
    # Verificar la sesión del usuario
    check = check_session(request)
    if not check:
        # Si no hay sesión válida, redirigir a la página de inicio de sesión
        return redirect('login')

    if request.method == 'GET':
        room_name = request.GET.get('room_name')
        if room_name:
            # Crear una nueva sala y redirigir a la sala recién creada
            new_room = Room.objects.create(name=room_name)
            return redirect('room', room_id=new_room.id)

    # Obtener las salas con mensajes y contar el número de mensajes e imágenes
    rooms = Room.objects.annotate(num_messages=Count('message')).filter(num_messages__gt=0)
    messages_count = Message.objects.filter(room__in=rooms, is_image=False).count()
    images_count = Message.objects.filter(room__in=rooms, is_image=True).count()

    # Obtener el nombre de usuario de la sesión o establecerlo como "Anónimo"
    username = request.session.get('username', 'Anónimo')

    context = {
        'rooms': rooms,
        'rooms_count': rooms.count(),
        'messages_count': messages_count,
        'images_count': images_count,
        'username': username,
    }
    return render(request, 'room_list.html', context)

# Vista de una sala
@csrf_exempt
def room(request, room_id):
    # Verificar la sesión del usuario
    check = check_session(request)
    if not check:
        # Si no hay sesión válida, redirigir a la página de inicio de sesión
        return redirect('login')

    # Obtener la sala correspondiente al ID proporcionado o mostrar una página de error 404 si no existe
    room = get_object_or_404(Room, id=room_id)
    messages = Message.objects.filter(room=room).order_by('-timestamp')[:50]

    image_url = None
    for message in messages:
        if message.is_image:
            image_url = message.image_url
            break

    if image_url:
        try:
            validators.URLValidator()(image_url)
        except ValidationError:
            image_url = None

    context = {
        'room': room,
        'messages': messages,
        'image_url': image_url,
    }
    return render(request, 'room.html', context)

# Vista para enviar un mensaje a una sala
@csrf_exempt
def send_message(request, room_id):
    # Verificar la sesión del usuario
    check = check_session(request)
    if not check:
        # Si no hay sesión válida, redirigir a la página de inicio de sesión
        return redirect('login')

    room = get_object_or_404(Room, id=room_id)
    sender = request.session.get('username', 'Anónimo')

    if request.method == 'PUT':
        # Procesar los datos del mensaje en formato XML



        xml_string = request.body.decode('utf-8')
        messages_data = xml_parser(xml_string)

        for message_data in messages_data:
            text = message_data['text']
            is_image = message_data['isimg']
            image_url = None

            if is_image:
                try:
                    validators.URLValidator()(text)
                    image_url = text
                    # Reemplazar el texto del mensaje con la etiqueta <img>
                    text = ''
                except ValidationError:
                    is_image = False

            # Crear y guardar la instancia de Message en la base de datos
            message = Message.objects.create(text=text, is_image=is_image)
            message.save()

        return redirect('room', room_id=room_id)

    elif request.method == 'POST':
        text = request.POST.get('message')
        is_image = bool(request.POST.get('is_image', False))
        image_url = request.POST.get('image_url', '')

        if is_image and text:
            try:
                validators.URLValidator()(text)
                image_url = text
                # Reemplazar el texto del mensaje con la etiqueta <img>
                text = ''
            except ValidationError:
                is_image = False

        message = Message(text=text, is_image=is_image, room=room, sender=sender)
        message.image_url = image_url
        message.save()

        return redirect('room', room_id=room_id)


# Función para procesar mensajes en formato XML
def xml_parser(xml_string):
    root = ET.fromstring(xml_string)
    messages = []
    for msg in root.findall('message'):
        isimg = msg.get('isimg')
        if isimg == "true":
            is_img = True
        else:
            is_img = False
        text = msg.find('text').text.strip()  # Eliminar espacios en blanco alrededor del texto
        messages.append({'isimg': is_img, 'text': text})
    return messages




# Vista de configuración del usuario
def configuracion(request):
    # Verificar la sesión del usuario
    check = check_session(request)
    if not check:
        # Si no hay sesión válida, redirigir a la página de inicio de sesión
        return redirect('login')

    if request.method == 'POST':
        new_username = request.POST.get('username')
        request.session['username'] = new_username

        font_size = request.POST.get('font_size')
        font_type = request.POST.get('font_type')

        # Guardar el tamaño y tipo de letra en la sesión del usuario
        request.session['font_size'] = font_size
        request.session['font_type'] = font_type

        return redirect('room_list')
    else:
        # Obtener los valores de tamaño y tipo de letra de la sesión
        font_size = request.session.get('font_size', '12px')
        font_type = request.session.get('font_type', 'Arial')

        # Obtener el nombre de usuario de la sesión o establecerlo como "Anónimo"
        username = request.session.get('username') or 'Anónimo'

        context = {
            'font_size': font_size,
            'font_type': font_type,
            'username': username,
        }
        return render(request, 'config.html', context)

# Vista de ayuda
def ayuda(request):
    # Verificar la sesión del usuario
    check = check_session(request)
    if not check:
        # Si no hay sesión válida, redirigir a la página de inicio de sesión
        return redirect('login')

    return render(request, 'help.html')

# Vista para obtener el favicon del sitio web
def get_favicon(request):
    favicon_path = os.path.join(settings.STATIC_ROOT, 'image/favicon.png')
    with open(favicon_path, 'rb') as favicon:
        response = HttpResponse(favicon.read(), content_type='image/png')
    return response

# Vista para obtener los mensajes de una sala en formato JSON
def messages_json(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    messages = Message.objects.filter(room=room).order_by('timestamp')

    messages_json = []

    for message in messages:
        message_data = {
            'author': message.sender,
            'text': message.text,
            'isimg': message.is_image,

project/DeCharla/templates/admin.html
{% extends 'base.html' %}

{% block content %}
  <h2>Panel de administración</h2>
  <p>Esta es una página de administración.</p>
{% endblock %}

project/DeCharla/templates/base.html
{% load static %}

<html>
<head>

    <link rel="icon" type="image/png" href="{% static 'image/favicon.png' %}" />

    <title>DeCharla</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
     <style>
        {% if request.session.font_size %}
            body {
                font-size: {{ request.session.font_size }};
            }
        {% endif %}

        {% if request.session.font_type %}
            body {
                font-family: {{ request.session.font_type }};
            }
        {% endif %}
    </style>
</head>
<body>
<header>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <a href="{% url 'room_list' %}" class="navbar-brand" id="logo">DeCharla</a>
            </div>
        </div>
    </div>
</header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item {% if request.path == '/DeCharla/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'room_list' %}">Principal</a>
                </li>

                <li class="nav-item {% if request.path == '/DeCharla/configuracion/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'configuracion' %}">Configuración</a>
                </li>
                <li class="nav-item {% if request.path == '/DeCharla/ayuda/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'ayuda' %}">Ayuda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin Site</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout_view' %}">Cerrar sesión</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<main>
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                    {% if not request.user.is_authenticated %}
                        <h2>Iniciar sesión</h2>
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            <div>
                                <label for="password">Contraseña:</label>
                                <input type="password" id="password" name="password">
                            </div>
                            <button type="submit">Iniciar sesión</button>
                        </form>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>



</main>

<footer class="bg-dark text-white">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p class="my-2">Mensajes: {{ messages_count }} Imágenes: {{ images_count }} Salas activas: {{ rooms_count }}</p>
            </div>
        </div>
    </div>
        <div class="container">
      <p>© 2023 Todos los derechos reservados.</p>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

project/DeCharla/templates/config.html
{% extends 'base.html' %}

{% block content %}
  <h1>Configuración de usuario</h1>

  <form method="post" action="{% url 'configuracion' %}">
    {% csrf_token %}
    <label for="username">Nuevo nombre de usuario:</label>
    <input type="text" id="username" name="username" value="{{ username }}">

    <h2>Cambiar tamaño y tipo de letra:</h2>
    <label for="font-size">Tamaño de letra:</label>
    <select id="font-size" name="font_size">
      <option value="12px" {% if font_size == '12px' %}selected{% endif %}>Pequeño</option>
      <option value="16px" {% if font_size == '16px' %}selected{% endif %}>Mediano</option>
      <option value="20px" {% if font_size == '20px' %}selected{% endif %}>Grande</option>
    </select>

    <label for="font-type">Tipo de letra:</label>
    <select id="font-type" name="font_type">
      <option value="Arial" {% if font_type == 'Arial' %}selected{% endif %}>Arial</option>
      <option value="Times New Roman" {% if font_type == 'Times New Roman' %}selected{% endif %}>Times New Roman</option>
      <option value="Verdana" {% if font_type == 'Verdana' %}selected{% endif %}>Verdana</option>
    </select>

    <button class="btn btn-primary" type="submit">Guardar</button>
  </form>

  {% if messages %}
    {% for message in messages %}
      <div class="{% if message.tags %}{{ message.tags }}{% else %}alert{% endif %}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

project/DeCharla/templates/help.html
{% extends 'base.html' %}

{% block title %}
Ayuda - DeCharla
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="title">Ayuda</h1>
  <p class="author">Autor: Christian Marina Villasevil</p>

  <div class="section">
    <h2 class="subtitle">Objetivo de la aplicación</h2>
    <p>
      El objetivo de la aplicación es la creación de una página web, la cual va a estar constituida por una lista de salas y un creador de salas.
      En la lista de salas veremos todas las listas que al menos tenga un mensaje en en la propia sala,
      y en el creador de las salas, cuando pongamos el nombre de una de las salas, nos redirigirá directamente a esa página.
    </p>
  </div>

  <div class="section">
    <h2 class="subtitle">Funcionalidades</h2>
    <p>
      Al principio, en el listado de salas, podemos observar un botón, el cual si pulsamos nos redirigiría a una pagina
      para observer los mensajes en formato JSON, con su autor, fecha, contenido del mensaje y si es una imagen o no.
    <p>
      Dentro de cada sala, podemos enviar dos tipos de mensajes, tanto mensajes de texto como imágenes.
      En la sala, podemos ver el nombre de las personas que están enviando los mensajes. También tenemos apartados
      como este mismo de ayuda, el apartado del Admin Site, configuración para poder cambiar el nombre de usuario con
      el que quieres mandar los mensajes y, por último, la opción de cerrar sesión (log out) para desloguearte.

    <p>
      También dentro de la sala observamos un boton 'Entrar a sala dinamica', el cual utilizamos para que la página web
      se nos vaya actualizando automaticamente cada 30 segundos, el resto es el mismo funcionamiento de una sala normal.
    </p>
  </div>

  <div class="section">
    <h2 class="subtitle">Inicio de sesión</h2>
    <p>
      Para iniciar sesión en la página, solo necesitas conocer la contraseña y que esa contraseña esté guardada.
      Una vez ingresada correctamente, podrás utilizar la página en su totalidad.
    </p>
  </div>
</div>
{% endblock %}

project/DeCharla/templates/index.html
{% extends 'base.html' %}



{% block footer %}
<footer class="bg-dark text-white">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p class="my-2">Mensajes: {{ messages_count }} Images: {{ images_count }} Salas activas: {{ rooms_count }}</p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

project/DeCharla/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
</head>
  <link rel="icon" type="image/png" href="{% static 'image/favicon.png' %}" />
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
<body>
  <h1>Bienvenidos a De Charla!</h1>
  <div class="form-container">
    <form method="post">
      {% csrf_token %}
      <h2>Iniciar sesión</h2>
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      <div>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password">
      </div>
      <button type="submit">Iniciar sesión</button>
    </form>
  </div>
</body>
</html>

project/DeCharla/templates/room.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>{{ room.name }}</h1>

  <div id="messages-container" style="height: 400px; overflow-y: scroll;">
    <div id="messages">
      {% for message in messages reversed %}
        <p>
          <strong>{{ message.sender }}:</strong> {{ message.text }}
          {% if message.is_image %}
              <img src="{{ message.image_url }}" style="width: 50%; height: auto;">
          {% endif %}
        </p>
      {% endfor %}
    </div>
  </div>

  <form id="message-form" method="POST" action="{% url 'send_message' room_id=room.id %}">
    {% csrf_token %}
    <input type="text" name="message">
    <label for="is_image">Es una imagen</label>
    <input type="checkbox" id="is_image" name="is_image">
    <button type="submit">Enviar</button>
  </form>

  <a href="{% url 'roomdin' room_id=room.id %}" class="btn btn-primary">Entrar a la sala dinámica</a>

  <script src="{% static 'js/room.js' %}"></script>

{% endblock %}

project/DeCharla/templates/room_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Salas disponibles</h1>
      <ul>
        {% for room in rooms %}
          <li>
            <a href="{% url 'room' room.id %}">{{ room.name }}</a> ({{ room.message_set.count }} mensajes)
            <a href="{% url 'messages_json' room.id %}" class="btn btn-sm btn-primary">JSON</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-md-4">
      <h2>Creador de salas</h2>
      <form method="GET" action="{% url 'room_list' %}" class="form-inline">
        <div class="form-group">
          <input type="text" name="room_name" class="form-control mr-2" placeholder="Nombre de la sala">
        </div>
        <button type="submit" class="btn btn-primary">Crear sala</button>
      </form>
    </div>
  </div>

  <div class="username">
    Usuario: {{ username }}
  </div>
{% endblock %}

project/DeCharla/templates/roomdin.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Sala dinámica: {{ room.name }}</h1>

  <div id="messages-container" style="height: 400px; overflow-y: scroll;">
    <div id="messages">
      {% for message in messages reversed %}
        <p>
          <strong>{{ message.sender }}:</strong> {{ message.text }}
          {% if message.is_image %}
              <img src="{{ message.image_url }}" style="width: 50%; height: auto;">
          {% endif %}

        </p>
      {% endfor %}
    </div>
  </div>

  <form id="message-form" method="POST" action="{% url 'send_message_din' room_id=room.id %}">
    {% csrf_token %}
    <input type="text" name="message">
    <label for="is_image">Es una imagen</label>
    <input type="checkbox" id="is_image" name="is_image">
    <button type="submit">Enviar</button>
  </form>
<a href="{% url 'room' room_id=room.id %}" class="btn btn-primary">Salir Sala dinámica</a>


  <script>
    src="{% static 'js/room.js' %}"
    // Función para descargar los mensajes en formato JSON y actualizar el elemento div
// Recargar la página cada 30 segundos
  setInterval(function() {
    location.reload();

  }, 30000);

  </script>
{% endblock %}